# Generated by Django 5.1.3 on 2024-11-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Числовое значение категории'),
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
