# Generated by Django 5.1.3 on 2024-11-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0002_remove_category_description_category_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_expense',
            field=models.BooleanField(default=True, verbose_name='Является расходом'),
        ),
    ]
