# Generated by Django 5.1.3 on 2024-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0003_category_is_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_expense',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
