# Generated by Django 5.1.3 on 2024-11-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0004_alter_category_is_expense_alter_category_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rate_to_base', models.DecimalField(decimal_places=4, default=1.0, help_text='Курс относительно базовой валюты (например, RUB=1.0)', max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency_code',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_per_user'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ms.currency'),
        ),
    ]
