# Generated by Django 5.1.3 on 2024-11-24 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
